### ISSUE TITLE
Check if code can be optimized

### ISSUE THREAD

**Issue by nitinkumar30** [Vasudha1905/internship_dataScience#1]
Please check whether your code can be optimized more in terms of **LOC(Lines Of Code)** & **time complexity.** 
Most of your codes can be optimized with proper _built-in modules/libraries_. Optimizing codes can be helpful when an application is handling large data or heavy traffic. 

Create a new version (1.1) for new optimized codes, once done.

**Comment by Vasudha1905** [comment]
I have optimized the codes and shared them in the v1.2branch.
