### ISSUE TITLE
Put random mini projects inside a directory

### ISSUE THREAD

**Issue by nitinkumar30** [Vasudha1905/internship_dataScience#2]
Put all the random files present inside **mini projects** folder to a folder for better code files arrangement. They're a part of **python basics** mini projects.

File structure  should be like "mini projects >> python basics" for above random files.

**Comment by Vasudha1905** [comment]
I have added all the mini projects to this [folder](https://github.com/Vasudha1905/internship_dataScience/tree/main/mini_projects/Python_Basics_)
